[package]
name = "lm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = {version = "0.32.2", features = ["serde-serialize"]}
serde = "1.0.160"
serde_json = "1.0.95"
